### ISSUE TITLE
Unable to debug spec from visual studio 2015

### ISSUE THREAD

**Issue by itsmemittal** [getgauge/gauge-visualstudio#198] opened 2017-09-07 07:54 UTC
I am re-posting this issue again because now I am consistently getting this issue.
Following i have installed
Gauge-Visual Studio Plugin - Version 0.3.1
Gauge - Version 0.9.1
Gauge-Csharp - Version 0.10.1

When open gauge project in visual studio 2015 i am getting following error.

[Debug] Opening Gauge Daemon for Project : RegressionAutomation, at ports: 1000, 2000
[Debug] Opening Gauge Daemon with PID: 17704
[Error] Failed to start Gauge Daemon: System.Exception: Could not connect ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:1000
at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
at Gauge.CSharp.Core.TcpClientWrapper..ctor(Int32 port)
--- End of inner exception stack trace ---
at Gauge.CSharp.Core.TcpClientWrapper..ctor(Int32 port)
at Gauge.VisualStudio.Core.GaugeService.StartGaugeAsDaemon(Project gaugeProject)

**Comment by itsmemittal** [comment] 2017-09-07 07:56
![image](https://user-images.githubusercontent.com/3033471/30152232-1b2beff4-93d0-11e7-9902-4ba3e19ef73b.png)

**Comment by Apoorva-GA** [comment] 2017-09-07 10:04
@itsmemittal Unable to replicate the issue with same plugin and gauge versions as of yours.
Could you please look at the logs directory in the project root and check `api.log` and `gauge.log` to check if there is any other information that could help.

**Comment by itsmemittal** [comment] 2017-09-08 13:09
Do we require gauge path to be set in User Environment variable?

**Comment by sguptatw** [comment] 2017-09-15 07:48
@itsmemittal : There is no need to set gauge path in the project properties - if that is what you meant by User Environment variable.

Also, Gauge 0.9.2 is released. Can you please let us know if you face the issue with the latest Gauge.
It will also help us if you can share your project or a dummy project where the issue is replicable.

**Comment by mura28info** [comment] 2017-09-19 04:26
@itsmemittal Update to last nightly build  **"0.9.3.nightly-2017-09-18"** from https://bintray.com/gauge/Gauge/Nightly . you should not get this error.
Duplicate of #200

**Comment by BugDiver** [comment] 2017-10-30 10:35
closing it since works fine with latest gauge and plugin. Feel free to open it if the issue still persists.

**Comment by EvanWoah** [comment] 2017-11-14 22:22
With the latest gauge plugin and latest version of gauge, I still face this issue regularly. Restarting my system sometimes works, or removing all specs for a moment- but I encounter this issue daily.

**Comment by sriv** [comment] 2017-11-15 01:20
@EvanWoah - could you please try with the [nightly version](https://bintray.com/gauge/Gauge.VisualStudio/Nightly/_latestVersion) of gauge-visualstudio plugin?

**Comment by EvanWoah** [comment] 2017-11-16 19:23
Thank you for the reply @sriv - I'll run with the Nightly version of the plugin for a few days, and report back.

**Comment by EvanWoah** [comment] 2017-11-16 21:31
@sriv still facing issue. Running Gauge 0.9.4. Nightly csharp plugin. 

[Debug] Opening Gauge Daemon for Project : RegressionAutomation,  at port: 46347
[Debug] Opening Gauge Daemon with PID: 8288
[Error] Failed to start Gauge Daemon: System.Exception: Could not connect ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:46347
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at Gauge.CSharp.Core.TcpClientWrapper..ctor(Int32 port)
   --- End of inner exception stack trace ---
   at Gauge.CSharp.Core.TcpClientWrapper..ctor(Int32 port)
   at Gauge.VisualStudio.Core.GaugeService.StartGaugeAsDaemon(Project gaugeProject, Int32 minPortRange, Int32 maxPortRange)
   at Gauge.VisualStudio.Core.GaugeService.RegisterGaugeProject(Project project, Int32 minPortRange, Int32 maxPortRange)
   at Gauge.VisualStudio.SolutionsEventListener.OnAfterOpenProject(IVsHierarchy pHierarchy, Int32 fAdded)

**Comment by sriv** [comment] 2017-11-17 01:18
@EvanWoah - one reason for the last error is that your Windows Firewall is blocking connection to `gauge.exe`. Please see this [wiki](https://github.com/getgauge/gauge-visualstudio/wiki/Troubleshooting#1-gauge-api-not-started) for some troubleshooting tips.

**Comment by EvanWoah** [comment] 2017-11-17 17:14
Yes - using the nightly version of the VS plugin. 
I misspoke, I use csharp plugin 0.10.1.

Firewall is not causing this. I have whitelisted the ports Gauge uses. Sometimes it loads properly, but other times  "Failed to start Gauge Daemon" occurs. Seemingly random.

**Comment by EvanWoah** [comment] 2017-11-21 15:44
Is there anything else I can try? The dameon will never load if I have 900+ specs, but if I reduce my spec count to 1, Gauge Dameon i more likely to load.

**Comment by sriv** [comment] 2017-11-21 16:21
@EvanWoah - that is strange. I do not have a large project with me, let me try setting one up and see if it is a cause. 

reopening this issue.

**Comment by sriv** [comment] 2017-11-30 09:32
Thanks @EvanWoah - your hint helped me reproduce the issue.

Problem is that on a large project, gauge sometimes takes a second (or two) to initialize it's cache and start accepting connections. Gauge-VisualStudio attempts to make contact in the interim, and gets a `SocketException`.

I created a project with 2500 specs and could see this happening.

I have pushed a fix, but that would also require gauge (0.9.6) to be released. In the meantime, could you please try gauge and gauge-visualstudio nightlies (>= 30/11/2017), and let me know if you still face the issue?

Appreciate your patience and help!

**Closed** 2017-12-06 05:20 UTC

**Comment by sriv** [comment] 2017-12-12 08:17
@EvanWoah - there is a new version of gauge-visualstudio (0.3.4), could you please try and see if this fixes your issue?

**Comment by EvanWoah** [comment] 2017-12-12 17:14
Certainly - will get back to you shortly.
