### ISSUE TITLE
parser should highlight inline tables with new lines

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/gauge-visualstudio#136] opened 2016-06-07 05:17 UTC
This is now valid step:

```
* Step that takes a table 

     | Product | Description                  |
     |---------|----------------------------- |
     | Gauge   | BDD style testing with ease  |
```

Refer getgauge/gauge#95.

**Comment by apoorvam** [comment] 2016-07-27 09:14
This issue is fixed in
Gauge version: 0.6.1
Gauge-Java: 0.4.2
Gauge IntelliJ plugin version: 0.2.2.nighty-2016-07-13

**Comment by BugDiver** [comment] 2016-12-20 10:50
Not able to reproduce. Expected behavior is working with the current release.

**Closed** 2016-12-22 06:37 UTC
