### ISSUE TITLE
Unable to create Gauge project from IDE

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#216] opened 2017-11-08 03:00 UTC
**Expected behavior**
If gauge and gauge-vs is installed I must be able to create a Gauge project from the IDE.

**Actual behavior**
Gauge project template does not appear in the test template List

**Steps to replicate**
* Open VS 2015. Try creating a project
* In the list of templates Gauge Project template does not appear.

**Version**
```
Gauge VS - nightly-2017-11-03
```
```
Gauge version: 0.9.4

Plugins
-------
csharp (0.10.2.nightly-2017-10-26)
html-report (4.0.2)
java (0.6.6.nightly-2017-09-14)
js (2.0.2)
ruby (0.4.3.nightly-2017-10-17)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

**Comment by sriv** [comment] 2017-11-09 05:29
Duplicate of #215.

**Closed by sriv** 2017-11-09 05:29 UTC
Labels: bug
