### ISSUE TITLE
SerializationException: There was an error deserializing the object of type Gauge.VisualStudio.TestAdapter.TestExecutionEvent. Encountered invalid character '	'. 

### ISSUE THREAD

**Issue by ssg47** [getgauge/gauge-visualstudio#253] opened 2019-04-27 07:52 UTC
### Expected behavior
No exceptions should be generated by the plugin after a successful build on value spec and step implementation files.

### Actual behavior
System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type Gauge.VisualStudio.TestAdapter.TestExecutionEvent. Encountered invalid character '	'. ---> System.FormatException: Encountered invalid character '	'.
   at [...] 

### Steps to reproduce
To recreate:

1. Create a new Gauge project.
2. Build the project (to trigger NuGet restore).
3. Open the StepImplementation.
4. Open the example.spec and use New Vertical Tab Group, so you can see both files.
5. In Test Explorer, click Run All.
6. See
```
------ Discover test started ------
Discover Scenarios started. Using : ProjectRoot: D:\Source\GaugeProject5\GaugeProject5, OutputPath: D:\Source\GaugeProject5\GaugeProject5\bin\Debug\, API Port: 46343
Adding test cases from : D:\Source\GaugeProject5\GaugeProject5\specs\example.spec
Discovered scenario: Vowel counts in single word
Discovered scenario: Vowel counts in multiple word
========== Discover test finished: 2 found (0:00:00.1559297) ==========
------ Run test started ------
Discover Scenarios started. Using : ProjectRoot: D:\Source\GaugeProject5\GaugeProject5, OutputPath: D:\Source\GaugeProject5\GaugeProject5\bin\Debug\, API Port: 46343
Adding test cases from : D:\Source\GaugeProject5\GaugeProject5\specs\example.spec
Discovered scenario: Vowel counts in single word
Discovered scenario: Vowel counts in multiple word
Executing Test: Vowel counts in single word
Executing Test: Vowel counts in multiple word
Invoking : gauge.exe - Arguments:run "D:\Source\GaugeProject5\GaugeProject5\specs\example.spec:14" "D:\Source\GaugeProject5\GaugeProject5\specs\example.spec:22" --machine-readable; ENV -  [redacted]
No test is available in D:\Source\GaugeProject5\GaugeProject5\specs\example.spec. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
========== Run test finished: 0 run (0:00:34.0609178) ==========
```
7. Edit ```* The word "gauge" has "3" vowels.``` to read ```* The word "gauge" has "4" vowels.```.  In a different recreating-the-problem project, this caused it to lose all of the tests and test explorer was empty.  In this case, it didn't work.  (One of the difficulties in reporting cases is that I don't get the same experience every time.)
8. Build the solution:
```
1>------ Build started: Project: GaugeProject5, Configuration: Debug Any CPU ------
1>  GaugeProject5 -> D:\Source\GaugeProject5\GaugeProject5\bin\Debug\GaugeProject5.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
9. I edited the above line back to 3, rebuilt and still couldn't recreate it (missing tests issue).  I think at this point, I closed the project and re-opened GaugeProject4 where I had the missing tests. Then closed and reopened this project.  I think I hit Build and it found all of the tests and then this appeared:
```
------ Discover test started ------
Discover Scenarios started. Using : ProjectRoot: D:\Source\GaugeProject5\GaugeProject5, OutputPath: D:\Source\GaugeProject5\GaugeProject5\bin\Debug\, API Port: 46346
Adding test cases from : D:\Source\GaugeProject5\GaugeProject5\specs\example.spec
Discovered scenario: Vowel counts in single word
Discovered scenario: Vowel counts in multiple word
========== Discover test finished: 2 found (0:00:00.1330083) ==========
------ Run test started ------
Discover Scenarios started. Using : ProjectRoot: D:\Source\GaugeProject5\GaugeProject5, OutputPath: D:\Source\GaugeProject5\GaugeProject5\bin\Debug\, API Port: 46346
Adding test cases from : D:\Source\GaugeProject5\GaugeProject5\specs\example.spec
Discovered scenario: Vowel counts in single word
Discovered scenario: Vowel counts in multiple word
Executing Test: Vowel counts in single word
Executing Test: Vowel counts in multiple word
Invoking : gauge.exe - Arguments:run "D:\Source\GaugeProject5\GaugeProject5\specs\example.spec:14" "D:\Source\GaugeProject5\GaugeProject5\specs\example.spec:22" --machine-readable; ENV -  [redacted]
System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type Gauge.VisualStudio.TestAdapter.TestExecutionEvent. Encountered invalid character '	'. ---> System.FormatException: Encountered invalid character '	'.
   at System.Runtime.Serialization.Json.XmlJsonReader.ComputeQuotedTextLengthUntilEndQuote(Byte[] buffer, Int32 offset, Int32 offsetMax, Boolean& escaped)
   at System.Runtime.Serialization.Json.XmlJsonReader.ReadQuotedText(Boolean moveToText)
   at System.Runtime.Serialization.Json.XmlJsonReader.Read()
   at System.Xml.XmlBaseReader.Skip()
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.SkipUnknownElement(XmlReaderDelegator xmlReader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   at ReadTestExecutionEventFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.InternalReadObject(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   at Gauge.VisualStudio.TestAdapter.GaugeRunner.OnOutputDataReceived(Object sender, DataReceivedEventArgs args)
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
   at System.IO.Stream.ReadWriteTask.InvokeAsyncCallback(Object completedTask)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Encountered invalid character '	'.
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   at Gauge.VisualStudio.TestAdapter.GaugeRunner.OnOutputDataReceived(Object sender, DataReceivedEventArgs args)
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
   at System.IO.Stream.ReadWriteTask.InvokeAsyncCallback(Object completedTask)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
No test is available in D:\Source\GaugeProject5\GaugeProject5\specs\example.spec. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
========== Run test finished: 0 run (0:00:30.4298283) ==========
```
Tests are greyed-out after this:
![image](https://user-images.githubusercontent.com/15728152/56846608-2d587d80-68c9-11e9-81c9-2972a1c7574f.png)

10. I ran Clean Solution, then Build Solution.  The tests were still greyed-out but I click Run All and they ran  successfully, went green in Test Explorer.  By the time I'd finished typing the above sentence they'd greyed-out again and the same (?) error message had appeared:
```
------ Discover test started ------
Discover Scenarios started. Using : ProjectRoot: D:\Source\GaugeProject5\GaugeProject5, OutputPath: D:\Source\GaugeProject5\GaugeProject5\bin\Debug\, API Port: 46346
Adding test cases from : D:\Source\GaugeProject5\GaugeProject5\specs\example.spec
Discovered scenario: Vowel counts in single word
Discovered scenario: Vowel counts in multiple word
========== Discover test finished: 2 found (0:00:00.1230029) ==========
------ Run test started ------
Discover Scenarios started. Using : ProjectRoot: D:\Source\GaugeProject5\GaugeProject5, OutputPath: D:\Source\GaugeProject5\GaugeProject5\bin\Debug\, API Port: 46346
Adding test cases from : D:\Source\GaugeProject5\GaugeProject5\specs\example.spec
Discovered scenario: Vowel counts in single word
Discovered scenario: Vowel counts in multiple word
Executing Test: Vowel counts in single word
Executing Test: Vowel counts in multiple word
Invoking : gauge.exe - Arguments:run "D:\Source\GaugeProject5\GaugeProject5\specs\example.spec:14" "D:\Source\GaugeProject5\GaugeProject5\specs\example.spec:22" --machine-readable; ENV -  VisualStudioDir:C:\Users\75031078SA\Documents\Visual Studio 2015 PUBLIC:C:\Users\Public JLP_Joined_Domain_Name:johnlewis.co.uk PROCESSOR_REVISION:1a05 PROCESSOR_IDENTIFIER:Intel64 Family 6 Model 26 Stepping 5, GenuineIntel ProgramData:C:\ProgramData SystemRoot:C:\WINDOWS JLP_NETBIOS_Domain_Name:NETDOM SCITE_USERHOME:C:\Users\75031078SA\AppData\Local\AutoIt v3\SciTE Path:C:\WINDOWS\system32;C:\WINDOWS;C:\Windows\PSTools;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Windows\idmu\common;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Microsoft Team Foundation Server 2012 Power Tools\;C:\Program Files (x86)\Microsoft Team Foundation Server 2012 Power Tools\Best Practices Analyzer\;C:\Program Files (x86)\WinMerge;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\dotnet\;C:\Program Files\Gauge\bin;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\ProgramData\chocolatey;C:\ProgramData\Oracle\Java\javapath;C:\Users\75031078SA\.dnx\bin;C:\Users\75031078SA\AppData\Local\Microsoft\WindowsApps;C:\Users\75031078SA\.dotnet\tools;C:\Users\75031078SA\AppData\Local\Programs\Fiddler ProgramFiles:C:\Program Files (x86) VS120COMNTOOLS:C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\ PATHEXT:.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC CommonProgramW6432:C:\Program Files\Common Files USERDOMAIN_ROAMINGPROFILE:NETDOM USERNAME:75031078SA USERPROFILE:C:\Users\75031078SA OS:Windows_NT VisualStudioEdition:Microsoft Visual Studio Community 2015 windir:C:\WINDOWS HOMEDRIVE:C: JLP_Server_Numeric:4 TVT:C:\Program Files (x86)\Lenovo MSBuildLoadMicrosoftTargetsReadOnly:true gauge_custom_build_path:D:\Source\GaugeProject5\GaugeProject5\bin\Debug\ LOGONSERVER:\\MCJS-DCBH3 SESSIONNAME:RDP-Tcp#12 JLP_Branch_Prefix:CS- UATDATA:C:\WINDOWS\CCM\UATData\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77 FPS_BROWSER_USER_PROFILE_STRING:Default CLIENTNAME:VI-LL12925 DEFLOGDIR:C:\ProgramData\McAfee\Endpoint Security\Logs USERDNSDOMAIN:NET.JOHNLEWIS.CO.UK APPDATA:C:\Users\75031078SA\AppData\Roaming PROCESSOR_ARCHITEW6432:AMD64 NUMBER_OF_PROCESSORS:8 VisualStudioVersion:14.0 BPADir:C:\Program Files (x86)\Microsoft Team Foundation Server 2012 Power Tools\Best Practices Analyzer\ _PTVS_PID:19540 PROCESSOR_ARCHITECTURE:x86 VSSDK100Install:C:\Program Files (x86)\Microsoft Visual Studio 2010 SDK SP1\ JAVA_HOME:C:\PROGRA~1\Java\jdk1.7.0_17 TMP:C:\Users\750310~1\AppData\Local\Temp\2 OPENSSL_CONF:C:\OpenSSL\bin\openssl.cfg CLASSPATH:JAVA_HOME\lib; PROCESSOR_LEVEL:6 SSISConfigConnectionString:Data Source=CS-SLS4GMK31;Initial Catalog=SSISConfig;Provider=SQLNCLI10.1;Integrated Security=SSPI;Auto Translate=False; VSLANG:1033 TEMP:C:\Users\750310~1\AppData\Local\Temp\2 FPS_BROWSER_APP_PROFILE_STRING:Internet Explorer CommonProgramFiles:C:\Program Files (x86)\Common Files ALLUSERSPROFILE:C:\ProgramData PSModulePath:C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files\WindowsPowerShell\Modules\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\Storage\;C:\Program Files (x86)\AutoIt3\AutoItX JLP_Branch_Mnemonic:CS ComSpec:C:\WINDOWS\system32\cmd.exe ChocolateyInstall:C:\ProgramData\chocolatey VS100COMNTOOLS:C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools\ WIX:C:\Program Files (x86)\WiX Toolset v3.11\ TFS_DIR:C:\Program Files\ThinkVantage Fingerprint Software\ TFSPowerToolDir:C:\Program Files (x86)\Microsoft Team Foundation Server 2012 Power Tools\ WispaBuildVersionPath:E:\Visual Studio Builds\Wispa ProgramW6432:C:\Program Files CommonProgramFiles(x86):C:\Program Files (x86)\Common Files LOCALAPPDATA:C:\Users\75031078SA\AppData\Local COMPUTERNAME:CS-SLS4GMK31 PkgDefApplicationConfigFile:C:\Users\75031078SA\AppData\Local\Microsoft\VisualStudio\14.0\devenv.exe.config USERDOMAIN:NETDOM VSSDK110Install:C:\Program Files (x86)\Microsoft Visual Studio 11.0\VSSDK\ HOMEPATH:\Users\75031078SA SystemDrive:C: VS110COMNTOOLS:C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\ JLP_RIS_Server:mcws-ut1 SHFBROOT:C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\ FP_NO_HOST_CHECK:NO ProgramFiles(x86):C:\Program Files (x86) VS140COMNTOOLS:C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\ JLP_Server_Dev_Lev:l
System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type Gauge.VisualStudio.TestAdapter.TestExecutionEvent. Encountered invalid character '	'. ---> System.FormatException: Encountered invalid character '	'.
   at System.Runtime.Serialization.Json.XmlJsonReader.ComputeQuotedTextLengthUntilEndQuote(Byte[] buffer, Int32 offset, Int32 offsetMax, Boolean& escaped)
   at System.Runtime.Serialization.Json.XmlJsonReader.ReadQuotedText(Boolean moveToText)
   at System.Runtime.Serialization.Json.XmlJsonReader.Read()
   at System.Xml.XmlBaseReader.Skip()
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.SkipUnknownElement(XmlReaderDelegator xmlReader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   at ReadTestExecutionEventFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.InternalReadObject(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   at Gauge.VisualStudio.TestAdapter.GaugeRunner.OnOutputDataReceived(Object sender, DataReceivedEventArgs args)
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
   at System.IO.Stream.ReadWriteTask.InvokeAsyncCallback(Object completedTask)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Encountered invalid character '	'.
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   at Gauge.VisualStudio.TestAdapter.GaugeRunner.OnOutputDataReceived(Object sender, DataReceivedEventArgs args)
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
   at System.IO.Stream.ReadWriteTask.InvokeAsyncCallback(Object completedTask)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
No test is available in D:\Source\GaugeProject5\GaugeProject5\specs\example.spec. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
========== Run test finished: 0 run (0:00:30.4298276) ==========
```

### Version Information

Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.03062

Installed Version: Community

Gauge.VisualStudio   1.0   (as reported by Help > About)
Gauge Visual Studio Extension

Gauge plugin for Visual Studio:- 0.3.7
Gauge.VisualStudio.Templates:- 1.1

```
gauge -v
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
csharp (0.10.5)
html-report (4.0.8)
json-report (0.3.1)
xml-report (0.2.1)

```

**Comment by nehashri** [comment] 2019-05-09 06:03
@ssg47 I wasn't able to see this error, but the the other issue on tests disappearing seems to be reproducible. I will see if this occurs after we fix the other issue

**Comment by Debashis9012** [comment] 2019-06-27 10:32
This issue has been verified and found fixed with the latest nightly of visual-studio.

**Closed by Debashis9012** 2019-06-27 10:32 UTC
Labels: bug
