### ISSUE TITLE
VS 2019 Plugin

### ISSUE THREAD

**Issue by medvedy** [getgauge/gauge-visualstudio#264] opened 2019-09-11 11:06 UTC
I'd appreciate a Visual Studio 2019 version of the plugin. Thanks a lot for your good work!

**Comment by nehashri** [comment] 2019-09-12 05:19
Duplicate of https://github.com/getgauge/gauge-visualstudio/issues/260.

@medvedy we do not have any plans to support VS 2019. Since the .Net Core (the gauge-dotnet) plugin is supported with Visual Studio Code, we will not be adding any more features in the the current VS plugin. We will also not add support VS 2019 in its current state.
Please look at migrating to Visual Studio Code to use the Gauge plugin.

**Closed** 2019-09-12 05:19 UTC

**Comment by bigjabird** [comment] 2019-10-22 19:54
if you will not support visual studios 2019 you should remove that functionality from the site

**Comment by sriv** [comment] 2019-11-07 06:30
@bigjabird - could you point me to any reference that conveys that VS2019 is supported? I'll correct it. Thanks.
